cmake_minimum_required(VERSION 3.21)
project(CppProjects)

set(CMAKE_CXX_STANDARD 23)

add_subdirectory(Algoritms)
add_subdirectory(AutoModelingNew)
add_subdirectory(AutoModelingExperiments)
add_subdirectory(AutoModelingTools)
add_subdirectory(BoostProject)
add_subdirectory(BoostTest)
add_subdirectory(BlockChain)
add_subdirectory(GoogleTests)
add_subdirectory(Collections)
add_subdirectory(Catch2Tests)
add_subdirectory(ContikiDCube)
add_subdirectory(CppSTDLibrary)
add_subdirectory(DataStructures)
add_subdirectory(DesignPatterns)
add_subdirectory(DiagnosticMethods)
add_subdirectory(EigenTests)
add_subdirectory(Encoding)
add_subdirectory(FuzzingExperiments)
add_subdirectory(FinTechMarketProjects)
add_subdirectory(LinuxExperiments)
add_subdirectory(MathLibrary)
# add_subdirectory(MatplotlibCpp)
add_subdirectory(OpenSSL)
# add_subdirectory(PocoProjects)
add_subdirectory(JsonCPP)
# add_subdirectory(QT_Projects)
add_subdirectory(MachineLearningExperiments)
add_subdirectory(Multithreding)
add_subdirectory(Networking)
add_subdirectory(RapidJSONTests)
add_subdirectory(Tests)
add_subdirectory(TestTask_OrderBook)
add_subdirectory(SSRC_TII_Experiments)
add_subdirectory(PerformanceExperiments)
add_subdirectory(DnsHEXConverter)
add_subdirectory(VTK_Experiments)
