cmake_minimum_required(VERSION 3.21)
project(CppProjects)

set(CMAKE_CXX_STANDARD 23)

# 5.15 - My home Ubuntu-20.04
if (CMAKE_SYSTEM_VERSION MATCHES "5.15")
    set(THIRD_PARTY_DIR /home/andtokm/DiskS/ProjectsUbuntu/third_party)
    set(EXTRA_LIBS tbb)
else()
    set(THIRD_PARTY_DIR /home/andtokm/Projects/third_party)
endif()

add_subdirectory(Algoritms)
add_subdirectory(BlockChain)
add_subdirectory(Collections)
add_subdirectory(CLI)
add_subdirectory(CppSTDLibrary)
add_subdirectory(DataStructures)
add_subdirectory(DesignPatterns)
add_subdirectory(EigenTests)
add_subdirectory(Encoding)
add_subdirectory(FuzzingExperiments)
add_subdirectory(FinTechMarketProjects)
add_subdirectory(Logging)
add_subdirectory(LinuxExperiments)
add_subdirectory(LinuxProcessManager)
add_subdirectory(MathLibrary)
# add_subdirectory(MatplotlibCpp)
# add_subdirectory(OpenCV)
add_subdirectory(OpenSSL)
add_subdirectory(JsonCPP)
add_subdirectory(MachineLearningExperiments)
add_subdirectory(Multithreding)
add_subdirectory(Networking)
add_subdirectory(Tests)
add_subdirectory(SSRC_TII_Experiments)
add_subdirectory(OptimisationPerformanceTuning)
add_subdirectory(PerformanceExperiments)
add_subdirectory(DnsHEXConverter)
add_subdirectory(Utilities)
