cmake_minimum_required(VERSION 3.21)
project(CppProjects)

set(CMAKE_CXX_STANDARD 26)

list(APPEND EXTRA_LIBS)
if (CMAKE_SYSTEM_VERSION MATCHES "5.15") # 5.15 - My home Ubuntu-20.04
    set(THIRD_PARTY_DIR /home/andtokm/DiskS/ProjectsUbuntu/third_party)
    list(APPEND EXTRA_LIBS tbb)
else()
    set(THIRD_PARTY_DIR /home/andtokm/Projects/third_party)
endif()

# Gcc-15 Experimental library symbols: 'Stacktrace'
list(APPEND EXTRA_LIBS stdc++exp)


add_subdirectory(Algorithms)
add_subdirectory(AlgorithmsTests)
add_subdirectory(Collections)
# add_subdirectory(Coroutines)
add_subdirectory(CLI)
add_subdirectory(CppSTDLibrary)
add_subdirectory(Databases)
add_subdirectory(DataStructures)
add_subdirectory(DataStructuresExperiments)
add_subdirectory(DesignPatterns)
add_subdirectory(EigenTests)
add_subdirectory(Encoding)
add_subdirectory(FuzzingExperiments)
add_subdirectory(FinTechMarketProjects)
add_subdirectory(Logging)
add_subdirectory(LinuxExperiments)
add_subdirectory(LinuxProcessManager)
add_subdirectory(MathLibrary)
# add_subdirectory(MatplotlibCpp)
# add_subdirectory(OpenCV)
add_subdirectory(OpenSSL)
add_subdirectory(Json)
add_subdirectory(MachineLearningExperiments)
add_subdirectory(Multithreding)
add_subdirectory(Networking)
add_subdirectory(Memory)
add_subdirectory(Tests)
add_subdirectory(OptimisationPerformanceTuning)
add_subdirectory(PerformanceExperiments)
add_subdirectory(Puzzles_BrainTeasers)
add_subdirectory(DnsHEXConverter)
add_subdirectory(Security)
add_subdirectory(SIMD)
add_subdirectory(Utilities)
add_subdirectory(UndefinedBehavior)
